//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IOT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Already Running!.
        /// </summary>
        internal static string AppAlreadyRunning {
            get {
                return ResourceManager.GetString("AppAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 적용.
        /// </summary>
        internal static string ApplyText {
            get {
                return ResourceManager.GetString("ApplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON files (*.json)|*.json|All files (*.*)|*.*.
        /// </summary>
        internal static string FileFilterConfig {
            get {
                return ResourceManager.GetString("FileFilterConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        internal static string IncorrectPasswordText {
            get {
                return ResourceManager.GetString("IncorrectPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file is empty or invalid..
        /// </summary>
        internal static string InvalidConfigFileOrEmpty {
            get {
                return ResourceManager.GetString("InvalidConfigFileOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT Connected Successfully..
        /// </summary>
        internal static string MqttConnectedSuccessfully {
            get {
                return ResourceManager.GetString("MqttConnectedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NILE Agent IoT.
        /// </summary>
        internal static string NILEAgentIoT {
            get {
                return ResourceManager.GetString("NILEAgentIoT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordPrompt {
            get {
                return ResourceManager.GetString("PasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a configuration file..
        /// </summary>
        internal static string SelectConfigFile {
            get {
                return ResourceManager.GetString("SelectConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string SubscribeText {
            get {
                return ResourceManager.GetString("SubscribeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown connection status..
        /// </summary>
        internal static string UnknownConnectionStatus {
            get {
                return ResourceManager.GetString("UnknownConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        internal static string UnsubscribeText {
            get {
                return ResourceManager.GetString("UnsubscribeText", resourceCulture);
            }
        }
    }
}
